package GUIs;

import Classes.*;
import java.util.ArrayList;
import java.util.Arrays;

public class GUI_Peregrino extends javax.swing.JFrame {
    final String FileRoute = "PeregrinosBinary.data";
    final String FileRouteCamino = "CaminosBinary.data";
    ArrayList<Peregrino> peregrino = FilesManager_bin.showListedPeregrinoFile(FileRoute);
    static int indexPe;

    public GUI_Peregrino(int index) {
        indexPe = index;
        initComponents();
        setLocationRelativeTo(null);
        NombreLabel.setText((peregrino.get(indexPe)).getNombre());
        IDLabel.setText(Integer.toString((peregrino.get(indexPe)).getID()));
        DomicilioLabel.setText((peregrino.get(indexPe)).getDomicilio());
        CaminoLabel.setText((peregrino.get(indexPe)).getCamino().getNombre());
        int counter = 0;
        Localidad[] localidades = (peregrino.get(indexPe)).getLocalidades();
        String[] someLocalidades = new String[localidades.length];
        for (int i = 0; i < localidades.length; i++){
            if(localidades[i] != null){
                someLocalidades[i] = localidades[i].getNombre();
                counter++;
            }
        }
        String[] LocalidadesRegistradas = new String[counter];
        System.arraycopy(someLocalidades, 0, LocalidadesRegistradas, 0, counter);
        LocalidadesTextArea.setText(Arrays.toString(LocalidadesRegistradas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        LocalidadesTextArea = new javax.swing.JTextArea();
        CaminoLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DomicilioLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 36, 76));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peregrino");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 40));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Localidades recorridas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Camino:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jButton2.setBackground(new java.awt.Color(37, 40, 70));
        jButton2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        LocalidadesTextArea.setEditable(false);
        LocalidadesTextArea.setBackground(new java.awt.Color(35, 36, 76));
        LocalidadesTextArea.setColumns(20);
        LocalidadesTextArea.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        LocalidadesTextArea.setForeground(new java.awt.Color(255, 255, 255));
        LocalidadesTextArea.setRows(1);
        LocalidadesTextArea.setBorder(null);
        LocalidadesTextArea.setRequestFocusEnabled(false);
        jScrollPane5.setViewportView(LocalidadesTextArea);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 690, 70));

        CaminoLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        CaminoLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(CaminoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 340, 30));

        NombreLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 30));

        IDLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, 30));

        jButton1.setBackground(new java.awt.Color(37, 40, 70));
        jButton1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver Camino");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Domicilio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        DomicilioLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        DomicilioLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(DomicilioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 340, 30));

        jButton3.setBackground(new java.awt.Color(37, 40, 70));
        jButton3.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Agregar Localidades");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        GUI_Principal pVisible = new GUI_Principal(indexPe);
        pVisible.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Camino> caminos = FilesManager_bin.showListedCaminoFile(FileRouteCamino);
        String unCamino = (peregrino.get(indexPe)).getCamino().getNombre();
        int indexCamino = FilesManager_bin.getIndexCamino(unCamino, FileRouteCamino);
        this.setVisible(false);
        GUI_Camino pVisible = new GUI_Camino(indexCamino);
        pVisible.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        GUI_RegisterLocalidades pVisible = new GUI_RegisterLocalidades(indexPe);
        pVisible.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CaminoLabel;
    private javax.swing.JLabel DomicilioLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextArea LocalidadesTextArea;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
