package GUIs;

import Classes.*;
import java.util.ArrayList;

public class GUI_Register extends javax.swing.JFrame {
    final String FileRoute = "PeregrinosBinary.data";
    final String FileRouteCamino = "CaminosBinary.data";
    
    public GUI_Register() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PasswordFieldClave = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        NombreTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        IDTextPane = new javax.swing.JTextPane();
        CaminosComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DomicilioTextPane = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peregrino");

        jButton2.setBackground(new java.awt.Color(37, 40, 70));
        jButton2.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 36, 76));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 40));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo Peregrino");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Camino:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        PasswordFieldClave.setBackground(new java.awt.Color(45, 36, 76));
        PasswordFieldClave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PasswordFieldClave.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PasswordFieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 170, -1));

        jScrollPane1.setBackground(new java.awt.Color(45, 36, 76));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        NombreTextPane.setBackground(new java.awt.Color(45, 36, 76));
        NombreTextPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NombreTextPane.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(NombreTextPane);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 210, 40));

        jScrollPane3.setBackground(new java.awt.Color(45, 36, 76));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        IDTextPane.setBackground(new java.awt.Color(45, 36, 76));
        IDTextPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        IDTextPane.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jScrollPane3.setViewportView(IDTextPane);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 210, -1));

        CaminosComboBox.setBackground(new java.awt.Color(45, 36, 76));
        CaminosComboBox.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        CaminosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camino Frances", "Camino Portugués", "Camino Inglés" }));
        jPanel1.add(CaminosComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 210, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing_Images/persona.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jButton3.setBackground(new java.awt.Color(37, 40, 70));
        jButton3.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Domicilio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jScrollPane4.setBackground(new java.awt.Color(45, 36, 76));
        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        DomicilioTextPane.setBackground(new java.awt.Color(45, 36, 76));
        DomicilioTextPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DomicilioTextPane.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jScrollPane4.setViewportView(DomicilioTextPane);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 210, -1));

        jButton4.setBackground(new java.awt.Color(37, 40, 70));
        jButton4.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Localidad[] newLocalidades = new Localidad[33];
        Camino newcamino = new Camino();
        ArrayList<Camino> caminos = FilesManager_bin.showListedCaminoFile(FileRouteCamino);
        System.out.println("\n\tRegistro Nuevo Peregrino");
        String unCamino = CaminosComboBox.getSelectedItem().toString();
        int y = FilesManager_bin.getIndexCamino(unCamino, FileRouteCamino);
        newcamino = caminos.get(y);
        String claveString = "";
        char[] clave = PasswordFieldClave.getPassword();
        for(int i = 0; i < clave.length; i++){
            claveString += clave[i];
        }
        Peregrino newPeregrino = new Peregrino(
                NombreTextPane.getText(), 
                Integer.parseInt(IDTextPane.getText()),
                claveString,
                DomicilioTextPane.getText(),
                newcamino,
                newLocalidades);
        FilesManager_bin.addRegister(newPeregrino, FileRoute);
        int index = FilesManager_bin.getIndexPeregrino(Integer.toString(newPeregrino.getID()), FileRoute);
        this.setVisible(false);
        GUI_RegisterLocalidades pVisible = new GUI_RegisterLocalidades(index);
        pVisible.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        GUI_Init pVisible = new GUI_Init();
        pVisible.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CaminosComboBox;
    private javax.swing.JTextPane DomicilioTextPane;
    private javax.swing.JTextPane IDTextPane;
    private javax.swing.JTextPane NombreTextPane;
    private javax.swing.JPasswordField PasswordFieldClave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
