package GUIs;

import Classes.*;
import java.util.ArrayList;

public class GUI_RegisterLocalidades extends javax.swing.JFrame {
    final String FileRoute = "PeregrinosBinary.data";
    final String FileRouteLocalidad = "LocalidadesBinary.data";
    static int indexRL;
    
    public GUI_RegisterLocalidades(int index) {
        indexRL = index;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaLocalidades = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo Peregrino");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 36, 76));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(45, 36, 76));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TextAreaLocalidades.setBackground(new java.awt.Color(45, 36, 76));
        TextAreaLocalidades.setColumns(20);
        TextAreaLocalidades.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        TextAreaLocalidades.setForeground(new java.awt.Color(255, 255, 255));
        TextAreaLocalidades.setRows(5);
        jScrollPane1.setViewportView(TextAreaLocalidades);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 490, 350));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 2, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Localidades Recorridas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jButton3.setBackground(new java.awt.Color(37, 40, 70));
        jButton3.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, -1, -1));

        jLabel1.setBackground(new java.awt.Color(35, 36, 76));
        jLabel1.setFont(new java.awt.Font("Roboto Thin", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   UNA localidad en cada línea");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        jLabel2.setBackground(new java.awt.Color(35, 36, 76));
        jLabel2.setFont(new java.awt.Font("Roboto Thin", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("* Registrar localidades con el nombre exacto (revisar sección Localidades)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 580, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList<Peregrino> newfile = new ArrayList<>();
        newfile = FilesManager_bin.showListedPeregrinoFile(FileRoute);
        Localidad[] newlocalidades = new Localidad[33];
        ArrayList<Localidad> localidades = FilesManager_bin.showListedLocalidadFile(FileRouteLocalidad);
        String unaLocalidad;
        Localidad[] currentlocalidades = newfile.get(indexRL).getLocalidades();
        int counter = 0;
        for (Localidad currentlocalidad : currentlocalidades) {
            if (!(currentlocalidad == null)) {
                counter++;
            }
        }
        System.arraycopy(currentlocalidades, 0, newlocalidades, 0, counter+1);
        if (TextAreaLocalidades.getText().contains("\n")){
            String[] lineas = (TextAreaLocalidades.getText()).split("\n");
            int i = counter;
            do{
                unaLocalidad = lineas[i];
                if (FilesManager_bin.findLocalidadinFile(unaLocalidad, FileRouteLocalidad)){
                    int j = FilesManager_bin.getIndexLocalidad(unaLocalidad, FileRouteLocalidad);
                    newlocalidades[i] = localidades.get(j);
                }
                i++;
            }while(lineas.length > i);
            (newfile.get(indexRL)).setLocalidades(newlocalidades);
            Object[] modifiedPeregrino = newfile.toArray();
            FilesManager_bin.addRegisters(modifiedPeregrino, FileRoute);
            this.setVisible(false);
            GUI_Principal pPrincipal = new GUI_Principal(indexRL);
            pPrincipal.setVisible(true);
        }else{
            try{
                unaLocalidad = TextAreaLocalidades.getText();
                if (FilesManager_bin.findLocalidadinFile(unaLocalidad, FileRouteLocalidad)){
                    int j = FilesManager_bin.getIndexLocalidad(unaLocalidad, FileRouteLocalidad);
                    newlocalidades[counter] = localidades.get(j);
                }
                (newfile.get(indexRL)).setLocalidades(newlocalidades);
                Object[] modifiedPeregrino = newfile.toArray();
                FilesManager_bin.addRegisters(modifiedPeregrino, FileRoute);
                this.setVisible(false);
                GUI_Principal pPrincipal = new GUI_Principal(indexRL);
                pPrincipal.setVisible(true);
            }catch(Error e){
                System.out.println("Error. " + e.getMessage());
            }            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaLocalidades;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}