package GUIs;

import Classes.*;
import java.util.ArrayList;

public class GUI_Albergue extends javax.swing.JFrame {
    final String FileRoute = "AlberguesBinary.data";
    final String FileRoutePeregrino = "PeregrinosBinary.data";
    static int indexA;
    
    public GUI_Albergue(int index) {
        indexA = index;
        initComponents();
        setLocationRelativeTo(null);
        ArrayList<Peregrino> newfile = new ArrayList<>();
        newfile = FilesManager_bin.showListedPeregrinoFile(FileRoutePeregrino);
        String currentCamino = newfile.get(indexA).getCamino().getNombre();
        ArrayList<Albergue> albergue = FilesManager_bin.showListedAlbergueFile(FileRoute);
        AlbergueTextArea.setText("Nro.\tNombre\tCapacidad\tPrecio\tLocalidad\n");
        switch(currentCamino){
            case "Camino Frances":
                int j1 = 1;
                for(int i = 1; i < 33; i++){
                    AlbergueTextArea.append((albergue.get(i-1)).formatRegister(j1) + "\n");
                    j1++;
                }
                break;
            case "Camino Portugués":
                int j2 = 1;
                for(int i = 34; i < 58; i++){
                    AlbergueTextArea.append((albergue.get(i-1)).formatRegister(j2) + "\n");
                    j2++;
                }
                break;
            case "Camino Inglés":
                int j3 = 1;
                for(int i = 59; i < 64; i++){
                    AlbergueTextArea.append((albergue.get(i-1)).formatRegister(j3) + "\n");
                    j3++;
                }
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AlbergueTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 36, 76));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(37, 40, 70));
        jButton3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALBERGUES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        AlbergueTextArea.setEditable(false);
        AlbergueTextArea.setBackground(new java.awt.Color(45, 36, 76));
        AlbergueTextArea.setColumns(20);
        AlbergueTextArea.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        AlbergueTextArea.setForeground(new java.awt.Color(255, 255, 255));
        AlbergueTextArea.setRows(5);
        jScrollPane2.setViewportView(AlbergueTextArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 810, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        GUI_Localidades pVisible = new GUI_Localidades(indexA);
        pVisible.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AlbergueTextArea;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
