package GUIs;

import Classes.*;
import java.util.ArrayList;

public class GUI_Camino extends javax.swing.JFrame {
    final String FileRouteCamino = "CaminosBinary.data";
    final String FileRouteEtapas = "EtapasBinary.data";    
    static int indexC;
    static int indexCPeregrino;
    
    public GUI_Camino(int index, int indexPeregrino) {
        indexCPeregrino = indexPeregrino;
        indexC = index;
        Camino newcamino = new Camino();
        ArrayList<Camino> caminos = FilesManager_bin.showListedCaminoFile(FileRouteCamino);
        newcamino = caminos.get(indexC);
        ArrayList<Etapa> newArrayEtapas = new ArrayList<>();
        newArrayEtapas = FilesManager_bin.showListedEtapaFile(FileRouteEtapas);
        String currentCamino = caminos.get(indexC).getNombre();
        initComponents();
        setLocationRelativeTo(null);
        NombreLabel.setText(currentCamino);
        KMLabel.setText(Double.toString((caminos.get(indexC)).getKm()));
        TiempoLabel.setText(Integer.toString(((caminos.get(indexC)).getTiempo())));
        EtapasTextArea.setText("Nro.\tNombre\t\tKm\tTiempo\tLocalidades\n");
        switch(currentCamino){
            case "Camino Frances":
                int j1 = 1;
                for(int i = 1; i < 33; i++){
                    EtapasTextArea.append((newArrayEtapas.get(i-1)).formatRegister(j1) + "\n");
                    j1++;
                }
                EtapasTextArea.append((newArrayEtapas.get(newArrayEtapas.size()-1)).formatRegister(34));
                break;
            case "Camino Portugués":
                int j2 = 1;
                for(int i = 34; i < 58; i++){
                    EtapasTextArea.append((newArrayEtapas.get(i-1)).formatRegister(j2) + "\n");
                    j2++;
                }
                EtapasTextArea.append((newArrayEtapas.get(newArrayEtapas.size()-1)).formatRegister(26));
                break;
            case "Camino Inglés":
                int j3 = 1;
                for(int i = 59; i < 64; i++){
                    EtapasTextArea.append((newArrayEtapas.get(i-1)).formatRegister(j3) + "\n");
                    j3++;
                }
                EtapasTextArea.append((newArrayEtapas.get(newArrayEtapas.size()-1)).formatRegister(6));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TiempoLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        KMLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EtapasTextArea = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 36, 76));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 550, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 550, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 130));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 0, 140));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Etapas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButton2.setBackground(new java.awt.Color(37, 40, 70));
        jButton2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tiempo(h):");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 40));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 2, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Camino");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        TiempoLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        TiempoLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, 30));

        NombreLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 30));

        KMLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        KMLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(KMLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, 30));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 40));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Km:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 40));

        EtapasTextArea.setEditable(false);
        EtapasTextArea.setBackground(new java.awt.Color(45, 36, 76));
        EtapasTextArea.setColumns(20);
        EtapasTextArea.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        EtapasTextArea.setForeground(new java.awt.Color(255, 255, 255));
        EtapasTextArea.setRows(5);
        jScrollPane2.setViewportView(EtapasTextArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 810, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        GUI_Peregrino pVisible = new GUI_Peregrino(indexCPeregrino);
        pVisible.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EtapasTextArea;
    private javax.swing.JLabel KMLabel;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JLabel TiempoLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
