package GUIs;

import Classes.*;
import java.awt.HeadlessException;
import java.util.ArrayList;

/**
 *
 * @author cristo
 */
public class GUI_LogIn extends javax.swing.JFrame {
    
    final String FileRoute = "PeregrinosBinary.data";
    ArrayList<Peregrino> peregrino = FilesManager_bin.showListedPeregrinoFile(FileRoute);
    int index = -1;
    
    /**
     * Creates new form GUI_Principal
     */
    public GUI_LogIn() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 36, 76));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Ingrese su ID:");
        jLabel2.setMaximumSize(new java.awt.Dimension(300, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 240, 190, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese su contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(45, 36, 76));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 247, 170, -1));

        jPasswordField2.setBackground(new java.awt.Color(45, 36, 76));
        jPasswordField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 180, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡Bienvenido!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 2, 44)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese a su cuenta de Camino de Santiago");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        String search = "";
        char[] cardCode = jPasswordField1.getPassword();
        for(int i = 0; i < cardCode.length; i++){
            search += cardCode[i];
        }
        index = FilesManager_bin.getIndexPeregrino(search, FileRoute);
        
        String validator = "";
        char[] password = jPasswordField2.getPassword();
        for(int i = 0; i < password.length; i++){
            validator += password[i];
        }
        Peregrino thisClient = peregrino.get(index);
        String ClientPassword = thisClient.getClave();
        try{
            if(!validator.equals(ClientPassword)){
                this.setVisible(false);
                GUI_Error pError = new GUI_Error("Incorrect password.", 0);
                pError.setVisible(true);
            } else {
                this.setVisible(false);
                GUI_Principal pPrincipal = new GUI_Principal(index);
                pPrincipal.setVisible(true);
            }
        }catch(HeadlessException e2){
            this.setVisible(false);
            GUI_Error pError = new GUI_Error(0,e2);
            pError.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_LogIn().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
